### ISSUE TITLE
Implement more thorough CommonJS/Node.js check

### ISSUE THREAD

**Issue by JamesMGreene** [Yuffster/Eve.js#21]
The current CommonJS/Node.js check for exporting isn't sufficient as it conflicts when Eve exists on a page where QUnit is loaded (as QUnit unfortunately has a global `module` function defined).

**Current export:**

``` js
if (this.module) this.module.exports = this.Eve;
```

**Some replacement options:**

``` js
if (typeof this.module !== 'undefined' && typeof this.module.exports !== 'undefined') {
  this.module.exports = this.Eve;
}
```

OR:

``` js
if (this.module && this.exports && this.module.exports === this.exports) {
  this.module.exports = this.Eve;
}
```

etc. etc.

**Comment by JamesMGreene** [comment]
P.S. I would've submitted a PR but I didn't know what style of fix you'd prefer for this, especially since you're byte-conscious. :)

**Comment by Yuffster** [comment]
Yeah, no problem the current codebase is a bit... special right now.

I'll get on it when I have a chance, thanks for the heads up!

**Comment by Yuffster** [comment]
Let's see if this does the trick. https://github.com/bgess/Eve.js/commit/94667f53c8b8ffafc5d8bd9967c307ff8791be51

Off the top of my head, feel free to re-open if necessary.  I'll test formally before the next build.

Thanks again for the report!

**Comment by JamesMGreene** [comment]
That should work in normal situations, yes. Thanks!
